---
name: EnderLevels
author: CaptainDuck
main: captainduck\EnderLevels\Main
version: 1.0.0
api: [3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12]
commands:
 stats:
  description: Shows your current stats!
  default: true
 addexp:
  description: Add experience to a player!
  usage: /addxp <player> <xp>
  default: op
 reduceexp:
  description: Reduce a player's experience!
  usage: /reducexp <player> <xp>
  default: op
 levelup:
  description: Level up with your current experience!
  default: true
  aliases: [levup, level]
...
